apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resiliencelab-artifacts
  labels:
    app: resiliencelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
